# Generated by Django 4.2.3 on 2024-08-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="cours_name",
            field=models.TextField(default="cours name"),
        ),
    ]
